Repository CodeLighthouse/sdk-python, pull requests merged in 2020-11, with the labels that each got.

#7 docs but signed this time
  docs/python/py_sdk_docs.md
Labels: documentation, enhancement

#8 Update README.md
  README.md
Labels: enhancement

#9 v0.1
  .github/workflows/python-publish.yml
  .gitignore
  LICENSE
  README.md
  codelighthouse/CodeLighthouse.py
  codelighthouse/CodeLighthouseWebHandler.py
  codelighthouse/__init__.py
  docs/python/py_sdk_docs.md
  example.py
  sdk/CodeLighthouse.py
  sdk/CodeLighthouseWebHandler.py
  setup.py
Labels: enhancement

#11 removed 'environment' from SDK documentation since it's for internal …
  docs/python/py_sdk_docs.md
Labels: bug, documentation

#12 change user agent
  codelighthouse/CodeLighthouseWebHandler.py
Labels: enhancement

#14 Update sdk example.py and logging
  codelighthouse/CodeLighthouseWebHandler.py
  example.py
Labels: documentation

#16 Update version number
  setup.py
Labels: enhancement

#18 Update documentation
  README.md
  codelighthouse/__init__.py
  docs/python/py_sdk_docs.md
  example.py
Labels: documentation, enhancement

#20 Merge to Prod
  README.md
  codelighthouse/__init__.py
  docs/python/py_sdk_docs.md
  example.py
Labels: enhancement

#27 Add printing on success
  codelighthouse/CodeLighthouseWebHandler.py
Labels: enhancement
